#!/usr/bin/env python

import os
import sys
import gi

gi.require_version('GnomeDesktop', '4.0')

from gi.repository import Gio, GnomeDesktop

def get_or_make_thumb(path):
    factory = GnomeDesktop.DesktopThumbnailFactory.new(GnomeDesktop.DesktopThumbnailSize.XLARGE)
    f = Gio.file_new_for_path(path)
    uri = f.get_uri()
    mtime = os.path.getmtime(path)

    thumb = factory.lookup(uri, mtime)

    if thumb is not None:
        return thumb

    info = f.query_info(
        "standard::content-type", Gio.FileQueryInfoFlags.NONE, None)
    mime_type = info.get_content_type()

    if not factory.can_thumbnail(uri, mime_type, mtime):
        return None

    thumb = factory.generate_thumbnail(uri, mime_type)

    if thumb is None:
        return None

    factory.save_thumbnail(thumb, uri, mtime)

    return factory.lookup(uri, mtime)

def main(argv):
    thumb = None

    if os.path.isfile(argv[1]):
        thumb = get_or_make_thumb(argv[1])

    if thumb is not None:
        print(thumb, end='\n')

if __name__ == "__main__":
    sys.exit(main(sys.argv))
